SELECT
COUNT(MUESTRA) AS No_Encuestados,
AVG(MUESTRA) AS PROM_ESTATURA,
AVG(PROMEDIO) AS PROMEDIO_IMC
FROM (
SELECT
ESTATURA AS MUESTRA,
AVG(IMC) AS PROMEDIO
FROM USERS
WHERE ESTATURA BETWEEN 1.60 AND 1.75
GROUP BY ESTATURA );